apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: image-mover-sample
    buildconfig: image-mover-sample
    name: image-mover-sample
    openshift.io/build-config.name: image-mover-sample
    openshift.io/build.start-policy: Serial
  name: image-mover-sample
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  serviceAccount: builder
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        stage 'build'
        //https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/index.html#docker-workflow

        docker.withServer("https://docker:2735") {
            docker.withRegistry("https://docker-registry.default.svc.cluster.local:5000") {
                docker.image("project1/img").pull
            }
            docker.image("project/img").tag
            docker.withRegistry("https://docker-registry.default.svc.cluster.local:5000"){
                docker.image("project/img").push
            }
        }
    type: JenkinsPipeline
  triggers: []
