apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: docker
  name: docker
spec:
  tags:
  - annotations:
      openshift.io/imported-from: docker
    from:
      kind: DockerImage
      name: 172.30.144.245:5000/jenkins2/docker:latest
    generation: 2
    importPolicy: {}
    name: latest