apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rabbitmq-deployment
spec:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - rabbitmq-autocluster
        from:
          kind: ImageStreamTag
          name: 'rabbitmq-autocluster:latest'
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-autocluster
        image: rabbitmq-autocluster:latest
        env:
          # For consupmption by rabbitmq-env.conf
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          # start.sh will store this value to a proper location in filesystem
          - name: ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: erlang.cookie
                key: erlang.cookie
        command:
          - "/start.sh"